### ISSUE TITLE
Filter attributes

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.AttributeUsageInspector#1]
Cool tool! 👍 
Even cooler if you could filter which attributes are displayed, `importsequencenumber` is usually not interresting, and if the primary key has less than 100% I would be surprised...

![image](https://cloud.githubusercontent.com/assets/2572253/18709481/ad22b5f8-8000-11e6-9477-d532d329c06e.png)

**Comment by MscrmTools** [comment]
I was sure you were the first to ask for extra features :)

And was sure that would be the first request

**Comment by rappen** [comment]
...but it was too hot to postpone the release.... ;)

**Comment by MscrmTools** [comment]
absolutely :-) I had to release it
