### ISSUE TITLE
Tool crashing with Contact entity

### ISSUE THREAD

**Issue by rksharma24** [MscrmTools/MscrmTools.AttributeUsageInspector#10]
[AttributeUsageInspector Error.docx](https://github.com/MscrmTools/MscrmTools.AttributeUsageInspector/files/2204439/AttributeUsageInspector.Error.docx)
Hi,

When using the AttributeUsageInspector in our environment, it crashes against the contact entity after running for a few minutes.
The entity has over 500K records and close to max in terms of # of fields (1K).

The error is:

[AttributeUsageInspector Error.docx](https://github.com/MscrmTools/MscrmTools.AttributeUsageInspector/files/2204441/AttributeUsageInspector.Error.docx)

Thanks,
Rocky.

**Comment by MscrmTools** [comment]
I guess this is a known issue and a PR has been submitted.
Let me release a new version today

**Comment by rksharma24** [comment]
thanks.
