### ISSUE TITLE
Usage only shows information based on 1 record

### ISSUE THREAD

**Issue by james-reinhardt** [MscrmTools/MscrmTools.AttributeUsageInspector#12]
Trying to retrieve information for Account records, only returning usage statistics based on 1 record. Have tried different settings but cannot get it to change.

**Comment by MscrmTools** [comment]
I just tested it again and it returned the appropriate number of records.
Can you tell me what is the number of records (approx.) it should have analyzed?

**Comment by james-reinhardt** [comment]
This was quite a while ago, I can't remember the specifics. However, I have used this plugin quite a few times over the last few weeks without having any issues, so I must have been doing something wrong back then. Sorry I didn't provide more detail than I did, I should know better ;).
