### ISSUE TITLE
Excel file missing data for two columns

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.AttributeUsageInspector#2]
It seems `Logical name` and `Attribute type` are not populated.

![image](https://cloud.githubusercontent.com/assets/2572253/18709606/40685138-8001-11e6-8252-6c3070edc5fc.png)

**Comment by MscrmTools** [comment]
Fixed!
Well, I changed the version number below the first release (I made a mistake) so I don't know if it will update correctly...
