### ISSUE TITLE
Export to Excel is missing data

### ISSUE THREAD

**Issue by dejandular** [MscrmTools/MscrmTools.AttributeUsageInspector#4]
In the Excel file there is a header, but the Logical name and Attribute type data is missing.

**Comment by MscrmTools** [comment]
This is known and fixed in a new release. Please update the plugin. If you don't see the update, please remove the file from Plugins folder and reinstall it.

**Comment by MscrmTools** [comment]
It seems Nuget cache is taking time to refresh... Maybe you'll have to wait to get the new version
