### ISSUE TITLE
Display name and logical name column not match in excel export

### ISSUE THREAD

**Issue by PirlotN** [MscrmTools/MscrmTools.AttributeUsageInspector#6]
Hello,

I want to warn you that the display name column get the logical name and the logical name column get the display name on the excel file.

The correction is simple. You just have to switch two line of code in ExcelEngine.cs file.

    29             sheet.Cells[i, 1].Value = "Logical name";
    30             sheet.Cells[i, 2].Value = "Display name"; 

to

    29             sheet.Cells[i, 1].Value = "Display name"; 
    30             sheet.Cells[i, 2].Value = "Logical name"; 

Best regards.

**Comment by MscrmTools** [comment]
Thank you, I will fix this
