### ISSUE TITLE
Limit to Attributes in Extracted Entity?

### ISSUE THREAD

**Issue by HaydnT** [MscrmTools/MscrmTools.AttributeUsageInspector#7]
Is there a hard-limit to the number of attributes associated with an entity that can be extracted via this tool?
Looking at our Incident table, which holds 385 attributes and the following exception error is generated. Other slightly smaller tables (Contacts, 285 entities) extract without issue.

************** Exception Text **************
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)

**Comment by MscrmTools** [comment]
I just added in latest version a parameter to set number of attributes to retrieve per call, try to play with this parameter to reduce the number of attributes per call to see if it works better

**Comment by MscrmTools** [comment]
Closing this issue because no feedback
